services:
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: secureeb24p
      MYSQL_DATABASE: prestashop-db
    volumes:
      - ./dbdata:/var/lib/mysql
    networks:
      - prestashop-net

  prestashop:
    platform: linux/amd64
    build:
      context: ./config
      dockerfile: Dockerfile
    image: prestashop/prestashop:1.7.8
    restart: unless-stopped
    environment:
      DB_SERVER: mysql
      DB_NAME: prestashop-db
      DB_USER: root
      DB_PASSWD: secureeb24p
      PS_INSTALL_AUTO: 
      PS_FOLDER_ADMIN: admXz5f9w7be
    ports:
      - "8080:80"
      - "443:443"
    networks:
      - prestashop-net
    volumes:
      - ./prestashop:/var/www/html
    depends_on:
      - mysql

networks:
  prestashop-net:
volumes:
  dbdata: