services:
  prestashop:
    image: jegji/bizele:presta
    environment:
      DB_SERVER: admin-mysql_db
      DB_NAME: BE_193333
      DB_USER: root
      DB_PASSWD: student
      PS_INSTALL_AUTO:
      PS_FOLDER_ADMIN: admXz5f9w7be
    ports:
      - "19333:443"
    networks:
      - admin-mysql_default
      - prestashop-net
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 512M

networks:
  prestashop-net:
  admin-mysql_default:
    external: true
