<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8rerylu\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8rerylu/appProdProjectContainer.php') {
    touch(__DIR__.'/Container8rerylu.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\Container8rerylu\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \Container8rerylu\appProdProjectContainer([
    'container.build_hash' => '8rerylu',
    'container.build_id' => '50d129f3',
    'container.build_time' => 1733685921,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8rerylu');
